apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: backend-tests-python-ptrbgizb
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/backend-tests-python-ptrbgizb:azure-9934e6d6ece396857490a655d6879b7f486c2225
          name: container-image
